### ISSUE TITLE
source directory missing '\' on windows

### ISSUE THREAD

**Issue by DrJMKatz** [orbikm/mkdocs-ezlinks-plugin#24] opened 2021-07-13 22:48 UTC
On windows, the src is missing the `\` between the source directory shorthand

```html
<img alt="image alt text" src="....\assets\images\image_20.png">
```
should be
```html
<img alt="image alt text" src="..\..\assets\images\image_20.png">
```

Should probably also make these `/` instead, even on Windows

**Comment by orbikm** [comment] 2021-07-19 19:55
Yeah, this should not be happening. I had fixed an issue where this was occurring previously, I may have accidentally caused a regression.

I'll do some digging on this soon. Thanks for reporting the issue!

**Comment by orbikm** [comment] 2021-07-26 02:33
Hi @DrJMKatz,

I am afraid I can not easily reproduce your issue. Can you please either describe your setup (or a contrived case) that demonstrates this issue, or provide an example of a site that exhibits this behavior?

**Comment by orbikm** [comment] 2021-08-23 16:52
Closing due to lack of information. If you have additional information for reproducing this bug, please feel free to re-open and I'll investigate.

**Closed by orbikm** 2021-08-23 16:52 UTC
Labels: bug, need more info
